### ISSUE TITLE
Simplify Admin search for individual product/category

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#5563] opened 2023-01-27 12:34 UTC
Right now if you go to Admin > Catalog > Categories/Products and enter "3" in the search box, you get 26 results. 

It would be great if you could somehow specify this is an id search, and only get (for example) product 3 and category 3 as results. 

I'm not specifying the mechanism to do this, just the desired result. 

This is further to @proseLA PR #5560.

**Comment by proseLA** [comment] 2023-01-27 15:38
simplify?  ha!

so apparently i did have what you wanted correct in our previous discussion.  i have given some more thought to this.  a few points to consider:

- while using the test data, your example may be correct, it is really misleading.  that is because the search results for products are limited by the constant `MAX_DISPLAY_SEARCH_RESULTS`, which in the test data is set to 20.  BUT the categories part of it is NOT limited.
- in my test data, with the #5560 merged, i get 3 categories and 27 products for the search.  total of 30.
- the pagination only works on the products, and the categories portion of the search repeats itself on every page.
- whether this was intended behavior or not, i can not say.
- in thinking about it, and in thinking about any potential future for ZC, i would think this is an opportunity for full stack development.  which means providing all of the results back to the page, and then controlling what the user sees based on various selections using some framework.
- this method would minimize the sql queries as well as the transferring of data back and forth.
- whether we currently have the technical foo on board to implement such a framework is questionable.

**Comment by scottcwilson** [comment] 2023-01-27 16:06
Not looking to boil the ocean here.  A checkbox saying "search IDs only" which would modify the query accordingly would do the trick.  KISS.

**Comment by scottcwilson** [comment] 2023-01-27 16:30
Look at how the orders page allows you to search by various fields in the order *or* just by the order id.  That's what we should do on the categories page.

**Comment by proseLA** [comment] 2023-01-29 00:04
> Look at how the orders page allows you to search by various fields in the order _or_ just by the order id. That's what we should do on the categories page.

someone thinks small; someone else thinks big....

the category/products page of code is almost 1300 lines of code.  adding more search fields onto the page is not what i would do.  

in addition, #5566 already gives one the ability to customize the search box.   i already have it working here:

![image](https://user-images.githubusercontent.com/1095136/215296740-b9056af4-2dc5-4525-a183-1924e6010282.png)

**Comment by scottcwilson** [comment] 2023-02-11 12:19
The request was "simplify individual product/category search." 
Would you please implement this?

**Comment by proseLA** [comment] 2023-02-12 02:51
> The request was "simplify individual product/category search." Would you please implement this?

#5573

**Comment by scottcwilson** [comment] 2023-02-12 11:40
Nice! I would say perhaps the checkboxes should be all on one line (floated right). 
My other question would be, does it make sense to have a "repopulate search terms" checkbox or should you just leave the search box filled with the last query and let people remove the contents if needed?  Not sure. 

Let's let @lat9 have a look, but I'd say merge this.

**Comment by proseLA** [comment] 2023-02-12 15:28
> Nice! I would say perhaps the checkboxes should be all on one line (floated right). 

please do NOT ever make css requests from me.  next time i will just ignore them.

bootstrap 3.4 is over 4 years old.  css is not my forte.  you want css changes?  do it yourself.

**Closed** 2023-02-16 18:15 UTC
