### ISSUE TITLE
Order Total Coupon minimum order amount / valid product

### ISSUE THREAD

**Issue by webelity** [zencart/zencart#1154] opened 2016-07-26 15:32 UTC
I ran into an issue where customers who have both restricted and non-restricted items in their cart. The message would tell the customer that they need to add at least $1.00 to their cart even if they have multiples. I have solved the issue by moving the code down below $foundvalid and adding two conditional statements to check if the item is valid and order meets the minimum order amount. 
I have verified that the code works on orders with both items (only valid products apply the discount amount). Can you apply this to future updates?

Just under this:
        // JTD - end of additions of missing code to handle coupon product restrictions

```
    if (strval($order_total['orderTotal']) < $coupon_result->fields['coupon_minimum_order'] && !$foundvalid) {
      $messageStack->add_session('redemptions', sprintf(TEXT_INVALID_COUPON_PRODUCT, $currencies->format($coupon_result->fields['coupon_minimum_order'])),'caution');
      $this->clear_posts();
      zen_redirect(zen_href_link(FILENAME_CHECKOUT_PAYMENT, '', 'SSL',true, false));
    }

    if (strval($order_total['orderTotal']) < $coupon_result->fields['coupon_minimum_order']  && $foundvalid == true)
    {
      $messageStack->add_session('redemptions', sprintf(TEXT_INVALID_REDEEM_COUPON_MINIMUM, $currencies->format($coupon_result->fields['coupon_minimum_order'])),'caution');
      $this->clear_posts();
      zen_redirect(zen_href_link(FILENAME_CHECKOUT_PAYMENT, '', 'SSL',true, false));
    }
```

**Comment by netcrop** [comment] 2016-07-27 03:29
1, I couldn't reproduce this issue before your change. 
I think the case below already taking care of this.
if ($coupon_result->fields['coupon_minimum_order'] > 0 && strval($order_total['orderTotal']) < $coupon_result->fields['coupon_minimum_order'])
2, Could you please show us how you did your test and your Coupon restriction rulls? I could be wrong.

**Comment by netcrop** [comment] 2016-07-27 10:08
GH-

**Comment by scottcwilson** [comment] 2016-08-16 10:41
@webelity Can you confirm that the repro steps that @netcrop used matched what you are describing?  If so, let's close this issue; otherwise please provide detailed repro steps and we can retest.  Thanks guys.

**Comment by scottcwilson** [comment] 2019-07-23 07:13
Can this issue be closed?

**Comment by scottcwilson** [comment] 2020-04-15 06:00
Many improvements have been made in this area, suggest closing this ticket.

**Closed** 2020-05-19 18:45 UTC
Labels: [Issue Type] Possible Bug, [location] catalog-side (storefront)
