### ISSUE TITLE
Discussion: Attributes System Improvements

### ISSUE THREAD

**Issue by bislewl** [zencart/zencart#766] opened 2016-01-06 22:32 UTC
Ok, I know we have all discussed this and we haven't really made progress on it. And this probably isn't the best place to discuss this. But several people have complained to me about the complexity of the Options/Values/Attributes Controller. One item being the inability to track stock. There are various modules out there that do support stock for attributes, and several people have suggested that being included in the core. It appears that the Attributes controller needs some improvement. Back in November of 2014 Ajeh and I discussed this. And I have been on/off trying to think of a way to improve it, how to make the entire Options/Values/Attributes controller system, easier and more intuitive. 

Does anyone have any thoughts?

**Comment by lat9** [comment] 2016-01-22 19:30
One thing that makes the attributes' entry a PITA is that first you enter the option names `one-by-one`, then the option-values `one-by-one` (re-selecting the option name each time) and *finally* the attributes themselves `one-by-one`.

The option-values entry could be changed to:
1) Select the option name to be updated, click OK
2) Present a full-page entry screen (i.e. you can change / add / remove) all option values and then click OK.

Use a similar approach on the attributes' entry.  Use the selection method as today (at least it's a multiple-select drop-down!) for the selected product and then present an edit screen where **all** the option-combination settings can be modified and then changed in one click.

**Comment by lat9** [comment] 2016-01-22 19:41
Another "feature" of the current attributes' support is that there's no means for re-use of a collection of attributes.  That can lead to "database bloat" if I've got a collection of products that always use the same attributes.

Say I've got a store that sells T-shirts.  All shirts are available in Sizes of S/M/L/XL and Colors of red/white/blue.  For each-and-every different shirt product in my store, those 12 attributes are repeated once per product.  It's probably my background (think 64Kb DOS), but I hate to see wasted storage.

**Comment by bislewl** [comment] 2016-01-22 19:41
I was looking at how other carts do it and I think I have a general idea. One of my concerns is if I do a complete overhaul, will that push people away OR will it draw more.
I saw another cart that actually allows you to modify the attributes (including add names/values) right from the product page. And allows you to track stock, it uses ajax, and drag/drop ability to change name/values and their ordering. To program this is little more labor intensive, than I can really invest at this time. However maybe just the basics would be helpful.

**Comment by wiztechinc** [comment] 2016-01-22 19:54
I consider this to be the biggest drawback with zen cart - especially if you need to track attributes stock. Learning the default system was only large chunk of admin that was very hard to wrap my head around. Now that I know it, I can prep my clients and get them past that hump. But for the do it your selfers out there, I really pity them. With difficulties in getting the attributes stock mod updated n the past, this becomes a priority for changes for me.

**Comment by bislewl** [comment] 2016-01-22 20:18
@lat9 what are your suggestions to avoid the "bloat" at the same time I would like to try and use the current tables, partly for upgrade reasons. So the new interface would need to be more intuitive. That's why I'm thinking Ajax may be a solution. It could utilize some of the same code as, and then just provide a nice interface.

**Comment by bislewl** [comment] 2016-01-22 20:27
@wiztechinc I agree, unfortunately I think it's something that turns people off. Do you have any ideas on a layout that you think would be easier for those new to zen-cart? There aren't any carts out there (at least from my research) that actually does it well. It's such a complex thing. For example in @lat9's example you have 12 variants of a single product, add other attributes like long/short sleeves. And the number of variants keeps growing rapidly. What are your thoughts for a "simple" way to provide an interface? IMHO in needs to be able to track stock. There has to be a way somehow to provide a interface that is easy for a newbie to understand in less than 15 mins. And provide all the desired functionality.

**Comment by lat9** [comment] 2016-01-22 20:31
@bislewl, in general, I'm thinking that there "must" be a way to associate a products_attributes table record with more than one product.  How that would work, both in presentation to the admin-user and the database "details", is still unclear to me.

**Comment by wiztechinc** [comment] 2016-01-22 20:39
Yes, the complexity is the issue. Having it all or as much as possible all on one screen makes it harder so I expect Ajax might be the answer. (though I'm no expert on coding) I haven't used any other program that does this where I needed to dig into this to have any real ideas about alternatives. I have used various incarnations of the stock by attributes mod and it had some easier interfaces at times but some of that is really long ago. What carts have you tried that had some simpler?

**Comment by bislewl** [comment] 2016-01-22 20:43
@lat9 In a vanilla version there is 6 tables for product attributes, even more for those that track stock. On the front end I think we should also add something like Dynamic Price Updater. That would help complete the circle.

**Comment by Zen4All** [comment] 2016-01-22 20:44
Be aware that is Ajax is used, some provision has to be taken for the 15 minute time-out. Otherwise work could get lost, resulting in frustration.
Incorporating a Dynamic Price Updater is a good idea, but the current DPU module has some ancient code in it.

**Comment by wiztechinc** [comment] 2016-01-22 20:47
Timing out can be a problem with anything that has massive changes - I have seen that with a mod - probably the dynamic price updater. I would like to see a timer added to the default admin - not just for that kind of thing.

**Comment by bislewl** [comment] 2016-01-22 20:53
@Zen4All Yes really some sort of notification that they need to log back in or something would need to be done. To my understanding each Ajax call should reset the 15 min timer correct?

DPU does have some ancient code and in a perfect world, I would spend time, and gut the entire module and then use the new Ajax system in 1.5.4. Any word on that coming into the admin? The need to add an additional admin page entry for each ajax page (so that non super users can use the functionality) would be helpful. It would probably just be fairly simple to copy and just change the few lines of code, so it references the admin? right?

**Comment by wiztechinc** [comment] 2016-01-22 21:03
I haven't tried Shopify (or at least not in years) but I do have to say that I have lost customers to it this past year whereas I rarely have lost clients before who switched out of zen cart.

**Comment by Zen4All** [comment] 2016-01-22 21:13
@bislewl I know 1.6.0 has this file zcAjaxHandler.php in the admin folder, so I guess it will be available by default. And If I remember correctly the new style of admin pages in 1.6.0 will also use Ajax

**Comment by bislewl** [comment] 2016-01-22 21:17
I haven't looked at 1.6.0 in a couple months, so perhaps I missed that.

**Comment by drbyte** [comment] 2016-01-22 21:54
Yes, the session timer will be reset on every ajax request.

**Comment by mc12345678** [comment] 2016-01-25 01:50
The discussion of moving various screen entries into an "earlier" screen certainly needs "on the spot" database access versus waiting for the data entered to be saved and the next screen loaded.  Something like ajax would address that.  The "reuse" of a selection of attributes for a product would involve another link table between product's attribute assignment and the table(s) containing the attributes.  

Part of what lat9 has been indicating is that as a user, what would you like to see on screen (areas to/from which to drag and drop, drop down menus, lists, buttons, screens that open up from the current screen, etc...)? Explaining/planning the user experience can help with the internal design and at least the interface.

While wiztechnic has at some point chosen to use the recent version of SBA and there were some limitations of that software (use of read-only attributes was a limiting factor that has since been overcome at the expense of some of the features added to make SBA more "informative" while development continues to overcome all of the options available with having read-only attributes associated); however, prior to the reincarnation of SBA (and more for those that are losing customers because of SBA inventory) there was a modification made to EasyPopulate V4 that will support maintaining/tracking inventory of a store that has SBA tracked inventory.  

The work of the difficulty discussed in this thread has to have already happened (either manually, or through some form of automated process), but once established can be updated like doing a "daily" inventory and without timeouts. Alas, in relation to the discussion of this thread it is unfortunately "outside" of ZC.

**Comment by IDEASGirl** [comment] 2016-04-20 16:22
Hi there, I just signed-up to give a bit of input on this discussion.

Before trying to bring the attributes page into the product input page, the product input page needs changes. These are things I don't know why they haven't been implemented in the last 3 upgrades of the platform:

- A "SAVE" button : WordPress has it, Joomla has it, even PrestaShop hast it; why ZenCart doesn't have it is beyond my mind. I don't understand why I have to click an "update" button, get out of the page to have to click again to continue my input. When you have a lot of information to enter for a product, you want that "SAVE" button there to assure you that is already safe in database (even if is not completed but you have main fields filled). I don't know why this hasn't been implemented, specially at the moment of the 15 minutes timeout.
- A "PREVIEW" button : Why I don't have a preview button that takes me to the page of that item I'm editing or entering? We know that the preview we get on 2nd page IS NOT the real WYSYWYG view of product page.

If these 2 things are implemented on the product input page; then the attributes and quantity discounts can be inserted into it by "tabs". I have some ideas on how should be displayed but sometimes making things simpler (in complex platforms like Zen Cart) is not easy to do, neither is always the best thing to do. I know nothing about programming, and for that reason is very difficult for me to say how to do it, I can only speak from the user side experience.

I will come back later with more input on how the attributes dynamic can be done.

**Comment by Zen4All** [comment] 2016-04-21 12:15
Although I like the idea of the save and preview button, for it to work a whole bunch of code needs to be changed. And this is probably the reason it has not been done yet.

**Comment by torvista** [comment] 2016-04-24 22:25
> Although I like the idea of the save and preview button, for it to work a whole bunch of code needs to be changed. And this is probably the reason it has not been done yet.
While this is off-topic, a very long time ago I changed the admin product/category listing so when categories are listed, the title of the parent category is a clickable link to the shop category and when products are listed, the id of the product is a clickable link to the product, which serves fine for me.

**Comment by torvista** [comment] 2016-04-24 22:31
> I was looking at how other carts do it and I think I have a general idea. One of my concerns is if I do a complete overhaul, will that push people away OR will it draw more.
If you mean if attributes support stock control will that get more ZC users?..I think this functionality hole is the single most important reason why today people should not choose Zen Cart for their new business. I wouldn't, if I was starting again.

**Comment by kerrinhardy** [comment] 2016-05-21 09:17
I had been following this discussion and, as it happens, my current assignment for the user-centred design course I am studying as part of a Bachelor of IT asks to review an application and redesign four functions using the user-centred design principles.  

Attached is a draft mockup of a redesigned product options page.  I am yet to write up the functions and associated screens, but was wondering if people following this issue have any comments and if you are happy for me to post updates as it progresses.

[Zen Cart Product Options Mockup v1.pdf](https://github.com/zencart/zc-v1-series/files/275790/Zen.Cart.Product.Options.Mockup.v1.pdf)

**Comment by lat9** [comment] 2016-05-21 12:08
Kerrin, the changes you've made are quire visually appealing, but reduce the functionality of the page.  You've removed settings (the sort order, size and length) from the main display, so I'd have to "dig" into each option one-by-one to determine that information.

I'd like to see **all** of the information bubbled up to the overall display (an indication as to whether there's a comment, and the attribute-image information), so I can "take in" the information in a single glance and can click that "Update" button if anything needs changing.

I imagine this page with a View/Update toggle so the the information is read-only in view-mode, but clicking *Update* turns the page into one big form where I can enter this information **all at one time** and not have to do the one-at-a-time entry (which is what my main beef is with most of the admin-level entry tools).

**Comment by kerrinhardy** [comment] 2016-05-21 14:44
If there was the concept of product option groups (similar to this: https://support.bigcommerce.com/articles/Public/Adding-Product-Options#how), would your requirement to edit in table form be for to edit all product options across the store or edit those within a product options group?

My thinking with the sort order at least was that it didn't make much sense to me to be across the entire store, but rather sort the options that are part of an options group.  I'll put more thought in to displaying a comment indicator, etc.

How do you feel about the global functions?  Is this something that could be accessed via an Advanced screen,  i.e. not displayed by default?

**Comment by lat9** [comment] 2016-05-21 16:39
@kerrinhardy, I see the value of having an `option-group` as it would make it easy to define a set of options that apply to multiple products -- *somewhat* mitigating the need for those "global options".   Wherever possible, I'd advocate an edit-all type form just to cut down on keystrokes and to give an overall view of the current settings.

I agree with your sort-order thinking as the current ZC approach makes it "very difficult" to have a set of products that use Size and Color (displayed in that order) and another set of products that use Material and Size (in that order).  Granted that you **can** do it, but it requires having two instances of the *Size* option each with different sort-orders.

I also believe that if any *revolutionary* approach is going to be taken for a future Zen Cart version (like adding the option-group concept), that it's imperative that the approach be designed from the top-down rather than piece-meal "fixing" the current interfaces.  That design should start with a documented set of requirements, features and workflows that define the "big picture" and the piece-wise implementation can then fulfill that "vision".

**Comment by mc12345678** [comment] 2016-05-21 16:50
To the first, I would say both, to apply sort order to the initial assignment such that when the items are pushed to the group(s) that there would already be sorted to some extent when adding to a llarger group and minimize the effort needed to reproduce sorted lists.  (This is currently accomplished through the sort order(s) of the option names and option values groups and furthered on the attributes controller).

As to the example page, that is a representation of the link (intermediate) table described above. It adds an additional item/aspect to the overall query process, but increases the flexibility of whaat can be added to the grouping.

The global functions, in my opinion, are something like how when installing ZC, just about everything is turned on to show the total options available (perhaps overwhelmingly so), but at least one doesn't have to go "find" the options.  In otherwords, I find now that frequently use ZC that there are options presented that are not needed, but when first being presented information, having it "in one's face" makes it easier to "find".

> I agree with your sort-order thinking as the current ZC approach makes it "very difficult" to have a set of products that use Size and Color (displayed in that order) and another set of products that use Material and Size (in that order). Granted that you can do it, but **it requires having two instances** of the Size option each with different sort-orders.

I disagree on that point, it does not require two size options for the provided example... Simply having a sort order for Size sufficiently high enough that Color can have a larger sort order and Material can have a smaller sort order.  Of course there does become a point where a specific option name set can not be so sorted, but the provided example is manageable without option name duplication.

**Comment by wiztechinc** [comment] 2016-05-22 17:28
I agree - don't patch. New approach only.

**Comment by scottcwilson** [comment] 2022-01-08 16:39
Closing due to lack of interest.

**Closed by scottcwilson** 2022-01-08 16:39 UTC
Labels: [Issue Type] enhancement
