### ISSUE TITLE
Installer PHP Notices:  Undefined index: db_charset

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3349] opened 2020-04-26 07:47 UTC
On db installation, three separate debugs:

> Undefined index: db_charset in D:\...\public_html\zencart-157\zc_install\ajaxTestDBConnection.php on line 25
> 
> Undefined index: db_charset in D:\...\public_html\zencart-157\zc_install\ajaxLoadMainSql.php on line 22
> Undefined index: db_charset in D:\...\public_html\zencart-157\zc_install\ajaxLoadMainSql.php on line 38
> 
> Undefined index: db_charset in D:\...\public_html\zencart-157\zc_install\includes\classes\class.zcConfigureFileWriter.php on line 34

**Comment by drbyte** [comment] 2020-04-26 22:46
This appears to be a duplicate of #3034

**Comment by torvista** [comment] 2020-04-27 07:09
Yes, I didn't find that when I searched.

**Closed** 2020-05-08 00:10 UTC
