### ISSUE TITLE
admin login page hard to read in 1.5.6 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zencart#1898] opened 2018-12-14 12:13 UTC
Could some smart guys with CSS skillz please fix this? @Zen4All ? 
<img width="465" alt="screen shot 2018-12-14 at 7 13 15 am" src="https://user-images.githubusercontent.com/4391638/50002909-c072c580-ff6f-11e8-9e3b-0ac8f893d99b.png">

**Comment by Zen4All** [comment] 2018-12-14 13:02
What is it you want fixed ??

**Comment by Zen4All** [comment] 2018-12-14 13:10
Do you mean font size, or contrast?

**Comment by scottcwilson** [comment] 2018-12-14 13:20
It's tiny!  Make it use the real estate on the screen.  Look at how much bigger the catalog side login is.

<img width="563" alt="screen shot 2018-12-14 at 8 19 59 am" src="https://user-images.githubusercontent.com/4391638/50005645-139d4600-ff79-11e8-9ae2-654d4ca46562.png">

**Comment by Zen4All** [comment] 2018-12-14 13:59
I'll put it on my to do list, but will until the dev will have moved the necessary changes from 1.5.6 to this branch. Or if they are okay it it let me port the login page in a PR.

**Comment by Zen4All** [comment] 2018-12-14 16:34
I thought you wanted the change in the dev branch. i will prepare a PR for 1.5.6

**Comment by scottcwilson** [comment] 2018-12-14 16:35
Sorry for the confusion.  Thanks for your efforts in this area.

**Comment by scottcwilson** [comment] 2018-12-14 16:36
@drbyte Any interest in allowing senior contributors to tag issues so as to make them more self-documenting?

**Comment by drbyte** [comment] 2018-12-14 17:21
> I am not certain what you're saying, but it's ok to fix issues like this in the 1.5.6 branch; there will be a follow on release to complete the PHP 7.2 changes. I have submitted several PRs already that have been merged.

Not sure what exactly you mean by "complete the PHP 7.2 changes".

And yes, while I've merged your PRs into the v156 branch I did it in order to capture fixes that might go into a bugfix release if one is deemed necessary.  While we may allow the occasional non-bug-"tweak" (like "Admin" text in tabs), I'm not encouraging everyone to do PRs to v156 except for confirmed bugs.

A PR to improve the admin login page is fine. I did a number of updates to that page to fix alignment issues in mobile and desktop. I'm surprised nobody mentioned it prior to release.

**Comment by dakanji** [comment] 2018-12-29 01:42
Pushed a PR against this.
Style looks like this:
![_zc admin login page](https://user-images.githubusercontent.com/1128876/50532015-dd88c600-0b23-11e9-9229-c1e01f31ec08.png)

Needs checking against items that only show up under specific conditions

**Comment by drbyte** [comment] 2018-12-29 09:08
@scottcwilson I still haven't run into a situation where the "too small" scenario has happened. In multiple browsers on multiple stores.

How exactly can this "problem" be triggered?

**Comment by Zen4All** [comment] 2018-12-29 10:11
Same here, iasked several people is they found the text to small. Got a lot of feedback for changes, but were size related.

**Comment by scottcwilson** [comment] 2018-12-29 12:08
Chrome, right click, Inspect, click phone icon on left to get it in mobile mode, select iphone 6/7/8.  Happens every time.

**Comment by Zen4All** [comment] 2018-12-29 14:08
Okay now I see what you mean.
maybe we should switch to icons instead of text?

**Comment by scottcwilson** [comment] 2018-12-29 18:19
To me if you just make it look like the catalog side login, that would be perfect.  The catalog side is just right.

**Comment by drbyte** [comment] 2019-01-03 13:38
Closed by #1987

**Closed by drbyte** 2019-01-03 13:38 UTC
