### ISSUE TITLE
[158] "Phantom" tax being displayed

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#4073] opened 2020-11-11 15:02 UTC
Running now-current zc158 with demo products.  Using the "Bill Smith" customer (based in CA), checking out there's a disparity in the order-total summation and the order's total:
![image](https://user-images.githubusercontent.com/2685585/98827391-cfd14680-2404-11eb-9ff4-3d55f542a6a1.png)

Viewing the placed order, it appears that a phantom 1% tax is being added:
![image](https://user-images.githubusercontent.com/2685585/98827504-f42d2300-2404-11eb-99c0-4f258ceda217.png)

**Comment by drbyte** [comment] 2020-11-12 20:09
Seems to be from 
https://github.com/zencart/zencart/blob/d181756b09d2a5960775429a59b68620b50f8c7e/includes/classes/order.php#L236

And its exposure is caused by my commit: https://github.com/zencart/zencart/commit/27696c599da9f22f9ad27f91a35aae62238b1b07

It would seem that it's associated with split-tax-rate features needing initialization ... which may need some improvement.

We can roll back my commit if it's actually the problem. But maybe there's another deeper issue that needs fixing as well.

Further exploration needed ...

**Comment by drbyte** [comment] 2020-11-12 20:38
I believe it's caused by my change here:
https://github.com/zencart/zencart/blob/v158/includes/functions/functions_taxes.php#L75

**Comment by drbyte** [comment] 2020-11-12 20:40
Fixed via https://github.com/zencart/zencart/commit/bfd4db7ed96fecf52964abcf81600dd8b08dbf66

**Closed by drbyte** 2020-11-12 20:40 UTC
