### ISSUE TITLE
zc157-beta: Copy Option Name/Value to Products with existing Option Name ...

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#3553] opened 2020-06-01 13:02 UTC
Attempting to use the "Copy Option Name/Value to Products with existing Option Name ..." feature.

I first made a copy of product id 59 (Hewlett Packard by Attributes) to the Music [62] category.  I then navigated to the **_Catalog::Option Values Manager_** and attempted to copy the "Orange" color's attribute from product 34 (A Bug's Life "Multi Pak" Special 2003 Collectors Edition):

![image](https://user-images.githubusercontent.com/2685585/83411073-86a4b180-a3e5-11ea-93bb-44d071b75fd2.png)

When I clicked the "Insert" button, I was redirected back to the home screen with the following URL:

`http://localhost/zc157b/nortH-tWN-braiN/index.php?options_id_from=1&options_values_values_id_from=25&copy_from_products_id=34&options_id_to=1&copy_to_categories_id=62&copy_attributes=copy_attributes_ignore`

No change was made to the attributes of that copied product.

**Comment by mc12345678** [comment] 2020-06-01 14:14
Looks like missing some sort of `cmd=xxx` parameter... What code section is supposed/expected to make the copy/insert?

**Comment by lat9** [comment] 2020-06-01 15:04
I'll note, also, that attempting this action on a zc156c installation simply refreshes the `attributes_controller` screen without message or performing the requested operation.

**Comment by drbyte** [comment] 2020-06-02 03:23
I haven't fully dug into all of this, but I have questions and observations:

This is for `action=copy_options_values_one_to_another_options_id`

- Do any other actions on that page actually work? This particular one is invoked via `zen_draw_form` the same as most others on this page are.

- `zen_draw_form` injects `cmd=` if the form method is `GET`. Otherwise not. Maybe there's something up with that?

**Comment by scottcwilson** [comment] 2020-06-02 08:27
Please make the above fix locally and retest - should be good.

**Comment by lat9** [comment] 2020-06-02 10:51
Now I get the following message:
![image](https://user-images.githubusercontent.com/2685585/83511807-3c7f0700-a49d-11ea-8853-3d9aba567601.png)

Am I misinterpreting what that form/action is intended to do?  I _thought_ that the processing should take the **_Color:Orange_** attribute from product id 34 and copy it to all products in category 62 that currently have a **_Color_** option.

**Comment by scottcwilson** [comment] 2020-06-02 10:53
I got that too and thought I might be using it wrong.  OK, so there are multiple issues.  I will keep digging - thanks.

**Comment by scottcwilson** [comment] 2020-06-02 13:30
OK this should be fixed too.  Note that a couple of permutations of this worked (if you had not specified category ID or if you had used the Update radio button), but I fixed the ones that didn't.

**Comment by drbyte** [comment] 2020-06-02 13:41
This may be a separate issue, but is `$attributes_image_name` a valid variable here? Is it actually handling the image correctly?
<img width="632" alt="Image 2020-06-02 at 9 38 32 AM" src="https://user-images.githubusercontent.com/404472/83526886-12d1da00-a4b5-11ea-87ce-1f5b7843d937.png">

**Comment by scottcwilson** [comment] 2020-06-02 13:54
That's also a bug. Possible root causes: 
a) The block that sets the defaults doesn't include this field
b) `$copy_from_products_id` is not set, so the query that builds the defaults doesn't work. 

I don't have any more time today.

**Comment by scottcwilson** [comment] 2020-06-02 14:01
The bugs I fixed were broken in 1.5.6.   This bug is even older.  We can move forward without fixing it.

**Closed** 2020-06-02 17:22 UTC
