### ISSUE TITLE
problem with zen_get_countries

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#4787] opened 2022-05-09 04:14 UTC
there is a problem with `zen_get_countries`.  

i am running zc158 and php 8.0 or php 8.1.  i am looking at the testdata with the following link:

https://zcdev.com/admin/index.php?cmd=configuration&gID=5

if the following key is not set: `SHOW_CREATE_ACCOUNT_DEFAULT_COUNTRY`, we get the following error:

```
[08-May-2022 21:01:47 America/Los_Angeles] PHP Fatal error:  Uncaught TypeError: zen_get_countries(): Argument #1 ($country_id) must be of type int, string given, called in /var/www/zcdev/includes/functions/functions_addresses.php on line 100 and defined in /var/www/zcdev/includes/functions/functions_addresses.php:50
Stack trace:
#0 /var/www/zcdev/includes/functions/functions_addresses.php(100): zen_get_countries()
#1 /var/www/zcdev/admin/includes/functions/general.php(439): zen_get_country_name()
#2 /var/www/zcdev/admin/configuration.php(145): zen_call_function()
#3 /var/www/zcdev/admin/index.php(11): require('...')
#4 {main}
  thrown in /var/www/zcdev/includes/functions/functions_addresses.php on line 50
```
the pulldown option when setting that value has an option for none.  setting it to none, sets that key value to an empty string.  if we were to set it to 0, it would not error out.  you can see the pulldown here:

![image](https://user-images.githubusercontent.com/1095136/167339236-df3077aa-7713-4f25-936f-7dfa134767c8.png)

finally besides us `modders` (actually i prefer the term `developers...`  but whatever floats your boat), i am not sure that the help text is very helpful.  i know 223 is the United States in zc.  but how would anyone else know that?  in addition, you can not set it to 223 via the pulldown.  you can set it to the United States...  i think you get my point...

![image](https://user-images.githubusercontent.com/1095136/167339515-f2a1f5aa-27ff-4779-9461-eacc155dfbb4.png)

**Comment by lat9** [comment] 2022-05-09 10:49
Isn't this a duplicate of #4734 ... other than the suggestion to change the setting's help text?

**Comment by proseLA** [comment] 2022-05-09 11:13
yes. it is.

**Closed** 2022-05-09 11:13 UTC
