### ISSUE TITLE
OSI image missing on new install help screen

### ISSUE THREAD

**Issue by proseLA** [zencart/zencart#3297] opened 2020-04-17 15:45 UTC
https://github.com/zencart/zencart/blob/0805d3d77f3e8660bea3da278b4dfa4a016bf728/includes/templates/template_default/templates/tpl_zc_install_suggested_default.php#L312-L319

there is no docs directory that i can tell.  so this image is missing.

in addition you might want to change the copyright to 2020

**Comment by scottcwilson** [comment] 2020-04-17 18:17
There is a docs folder. The image is fine.  See attached. 
You are correct the date needs updating or perhaps just use PHP to show current year. 

![image](https://user-images.githubusercontent.com/4391638/79600983-14d30b80-80b6-11ea-960a-6b76d845e9e5.png)

**Comment by scottcwilson** [comment] 2020-04-17 18:21
OK the file includes/templates/template_default/templates/tpl_zc_phpupgrade_default.php uses PHP to show the current year.  Will use that standard to fix this issue.

**Comment by proseLA** [comment] 2020-04-17 18:40
> There is a docs folder. The image is fine. See attached.
> 
scott,
i'm not sure what to tell you.  you want people to test the v157 install process.  i downloaded the zip, the first page is the one that came up and it is prior to the inspection page.  it asks if you want to install or something like that.  at the bottom of the page is where the copyright is.  this is the first thing that i see when trying to install v157.  and the image is not there.  

frankly, if i was a store owner trying out ZC for the first time, and the very first thing i see has a link to a broken image, it would not give me any confidence in the rest of the project.

you know in looking at this closer, it becomes pretty apparent that on line 312 that i have pointed out, there is a missing period, which is why that image does not come up.  perhaps you can fix that as well.

**Comment by scottcwilson** [comment] 2020-04-17 18:56
If I reference path starting with "./docs" - current state 
<img src="./docs/osi-certified-120x100.png"
it works.

If I reference path with starting with "docs"
<img src="docs/osi-certified-120x100.png"
it works.

If I reference path starting with "../docs" as you suggest: 
<img src="../docs/osi-certified-120x100.png"
it fails.

**Comment by scottcwilson** [comment] 2020-04-17 18:58
Also: The zip file doesn't include the docs.   The zip, a fork of the project, and the final installable file all are slightly different.

**Comment by proseLA** [comment] 2020-04-17 19:09
what OS are you using?

the zip that i downloaded includes the docs.  and it is one level above the zc_install folder.

2 dots as in:
`<img src="../docs/osi-certified-120x100.png">`

is very common in the linux world to refer to one directory up from where you are.  the use of 2 dots and a slash is used throughout this project.

**Comment by drbyte** [comment] 2020-04-18 18:08
@proseLA wrote:
> there is no docs directory that i can tell. so this image is missing.

Yes and no.

If you downloaded the v1.5.7 zip from github directly, as a "Download zip of this branch", then you'll NOT get the "docs" directory. That's because it's excluded from github's generated zips because of a rule we set in https://github.com/zencart/zencart/blob/v157/.gitattributes

However, if you download Zen Cart from an official distribution point such as SourceForge, you'll get the "docs" directory included.

**Comment by scottcwilson** [comment] 2020-04-18 18:24
@drbyte Can you repro the issue @proseLA reported?  I'll fix it if you can show me how to repro it but it worked for me in testing.

**Comment by drbyte** [comment] 2020-04-18 18:29
> @drbyte Can you repro the issue @proseLA reported?

Yes. Delete or rename these:
- /docs
- /includes/local/configure.php
- /includes/configure.php

Similarly with admin configure.php's ... but not necessary to reproduce the situation.

**Comment by drbyte** [comment] 2020-04-18 18:30
I guess the fix could be to copy the image to the zc_install/includes/templates/images dir

**Comment by scottcwilson** [comment] 2020-04-18 18:31
renaming /docs seems like a bit of an unfair test ... I clobbered the contents of includes/configure.php and the image still worked.

**Comment by drbyte** [comment] 2020-04-18 18:32
See my point above about obtaining the zip via github. It happens.

**Comment by scottcwilson** [comment] 2020-04-18 18:34
I see your point.  OK, noodle on it and if you still feel the approach of moving it to zc_install is the way to go, I can put in a fix.

**Comment by scottcwilson** [comment] 2020-04-18 18:35
I kind of think we should change `.gitattributes` but I'll do whatever you decide.

**Comment by drbyte** [comment] 2020-04-18 18:38
I'm pretty sure we excluded the docs from that zip generation process just to stop cluttering the dir with files unnecessary if you're dealing directly with source code. ie: if you're working on github you know how to find the docs on github, and you probably appreciate not needing to clean up/remove the extra docs dir when uploading to the server. Plus it helps avoid disclosing what version is installed, even if only slightly.

Let's copy the image to zc_install and update the reference accordingly  in the tpl file. 
(All the links to that image in the docs dir can stay the same as they are now if we only "copy" the image, and not "move" it.)

**Comment by scottcwilson** [comment] 2020-04-19 06:18
> if you're working on github you know how to find the docs on github, and you probably appreciate not needing to clean up/remove the extra docs dir when uploading to the server. 

You still have a bunch of cleanup to do: extras, zc_install, install.txt.  
I fixed this so that in case the docs folder gets clobbered, the image still works, but I think the docs folder should be included in the zip download.  I was quite astonished by its absence.

**Comment by torvista** [comment] 2020-04-19 06:32
I would have expected Clone and the .zipped download to be identical since they are OR options on the same button. I would never have imagined a difference.
Indeed, anyone wanting to try this out rather than look at the code (the majority of **users**) will choose .zip and then probably wonder where the documentation is. In my opinion it should be complete/equal to the clone and nothing is gained by omitting it.

**Closed** 2020-04-19 16:02 UTC

**Comment by scottcwilson** [comment] 2020-04-20 05:25
Issue resolved by including docs in the zip download.
