### ISSUE TITLE
admin, languages: An unknown response was received while processing an ajax call

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#1063] opened 2016-07-05 09:47 UTC
when entering a character in the filter box, the ajax message pops up.

**Comment by zcwilt** [comment] 2016-07-05 14:18
I can't reproduce this on a clean install.
Is it possible that the session timed out.

**Comment by zcwilt** [comment] 2016-07-05 14:40
See https://github.com/zencart/zencart/issues/1066
which I've just opened

**Comment by torvista** [comment] 2016-07-05 16:18
(Windows 10/php 7.04/xampp 7.04)
I log into admin, go straight to currencies for example and type something in the filter box, immediately the ajax error pops up. The session info is in a cookie I assume? What else to look for with dev tools?

**Comment by zcwilt** [comment] 2016-07-05 16:22
You may be suffering from https://github.com/zencart/zencart/issues/516

**Comment by torvista** [comment] 2016-07-05 22:07
enabling/disabling gzip in the admin options has no effect.
This is the obkect, if that is any htlp:

**Comment by scottcwilson** [comment] 2016-07-07 23:42
This only happens in PHP7 it seems.  I can dup it by typing something into a filter and then doing command R to get a page refresh.

**Comment by drbyte** [comment] 2016-07-07 23:45
I'm not seeing it on linux (ubuntu and debian) sites running PHP 7.0.8

**Comment by torvista** [comment] 2016-07-08 22:46
I see it on Xampp Windows 10 php 5.6.8 and 7.0.4.
Local server uses virtual hosts setup.
I attach the console output which may be of help which shows the result of a page refresh (no error) and the result of putting the cursor in the field (error), my comments near the end.
[console_output.txt](https://github.com/zencart/zencart/files/355222/console_output.txt)

**Comment by torvista** [comment] 2016-07-09 10:57
Using today's files I tried this locally Windows 10, Xampp FFox, Chrome, IE, Edge, Opera,
php 5.6.8 - error
php 7.0.4 - error
php 7.0.8 - error
and also on real hosting with the identical fileset
php 5.5.32 Linux 2.6.18-448.16.1.el5.lve0.8.70 - no error

So could be windows, could be my apache config:
I access the site locally using this
www.motorvista.dev
this is redirected in the hosts file to 127.0.0.1 
and the apache virtual host config redirects to the files location.
SSL is in use but using the included xampp certificate: every browser complains on first access that the cert is invalid, I continue anyway and all seems ok. 
I have been using this setup for a very long time with no other issues, even url rewriting works fine.

**Comment by zcwilt** [comment] 2016-07-09 15:40
Do you have firebug installed in your Firefox instance

**Comment by zcwilt** [comment] 2016-07-09 15:48
Another thing you could try is to disable CDN loading for jquery
e.g. In admin/includes/temlplate/common/tplHtmlHead.php 

remove the lines 

    <script src="//code.jquery.com/jquery-2.2.4.min.js"></script>

and 

    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>

**Comment by torvista** [comment] 2016-07-10 08:49
Just to check the basics, there are no other auxiliary files necessary that need to be added into the ZC 160 cloned zip download?

**Comment by drbyte** [comment] 2016-07-10 16:58
Correct. It functions as is.

**Comment by scottcwilson** [comment] 2016-07-10 17:08
When I turn on Chrome debugging tools, the console message I get when I do a refresh is zcJSFramework.js:34 Object{readyState:0, responseJSON: undefined, status: 0, statusText:"error}  

I *can* dup this in PHP 5.6 using the following steps:
- Go to admin->localization->currencies
- type random text in the Currencies filter box (doesn't match anything)
- do a refresh

**Comment by drbyte** [comment] 2016-07-10 18:53
Thanks Scott. While I can't trigger it consistently, I have been able to trigger it occasionally. Definitely requires the "refresh", which is odd given this is an ajax call.

Line 34 of that file is simply attempting to log data to the console if an error occurs. 
```js
              console.log(jqXHR);
```

I wonder if the fact that everything other than the console.log action is being deferred has anything to do with it? 
And I wonder if logging something more specific than the `jqXHR` object would be more relevant here, anyway.

**Comment by torvista** [comment] 2016-07-10 21:25
Note that in my setup the error triggers instantly and every time on placing the cursor in any of the filter fields.
I've tried it in the Xampp root, no aliases or virtual hosts or redirects, same error.

I setup an old Xampp (php 5.3.1) on a spare XP machine, same error symptoms.

Since no-one else is seeing the error consistently, if required the XP laptop can be made available for a remote session with Teamviewer, pm me via the forum for access.

**Comment by scottcwilson** [comment] 2016-07-10 21:32
I do see it consistently in my config.

**Comment by drbyte** [comment] 2016-07-10 23:22
Commenting out the line stops the message, but doesn't resolve the root problem. 
I would think that it's still prudent to log errors to the console if errors-worth-trapping occur.

**Comment by zcwilt** [comment] 2016-07-11 09:26
https://developer.mozilla.org/en/docs/Web/API/Console/log

http://stackoverflow.com/questions/4946287/finding-out-if-console-is-available

**Comment by zcwilt** [comment] 2016-07-11 09:31
Personally, I wouldn't be bothered if the console.log was removed completely

**Comment by zcwilt** [comment] 2016-07-11 15:01
k, So I have been able to duplicate this on my main Ubuntu development machine,
albeit just with the Refresh so far. 

What appears to be happening is that an out of memory exception is occurring, and this is triggering the Ajax error.

**Comment by zcwilt** [comment] 2016-07-11 15:16
Further update. The refresh bug only occurs if you hit refresh before all  of the ajax calls return 
e.g. if I type abcdefg then 8 ajax calls are started.
if some of the calls haven't completed then I get the error. 
If I wait for all the calls to complete, I don't get any errors.
So probably not related to @torvista

**Comment by zcwilt** [comment] 2016-07-11 15:18
I also set up wampserver on my spare Windows 10 laptop and haven't been able to reproduce :(

**Comment by zcwilt** [comment] 2016-07-11 17:55
@torvista  thanks for the teamviewer access.

I've played around on the server, but really only to confirm your error.
While I do see some messages related to ssl certificates, don't think this is contributing to the error.
And I'm not seeing anything else in Firebug that suggests a solution.

What is interesting is that the dashboard widgets drag/drop work fine. Given that they also use ajax to fire position updates, I will look at the differences in code for firing ajax between dashboard and LEAD filters.

**Comment by zcwilt** [comment] 2016-07-11 18:00
And also the Select2 stuff is working as well

**Comment by zcwilt** [comment] 2016-07-11 18:02
@torvista One question. Have you in the past had working filter stuff in v160

**Comment by zcwilt** [comment] 2016-07-11 18:35
But there my have been changes we made to ajax infrastructure/htaccess etc that broke windows support. 

> But since this all works on real hosting I would have suspected the issue to be not the code but something to do with the local/Windows/Xampp environment.

The fact that it works on real hosting and breaks on Wamp doesn't preclude code being wrong

**Comment by scottcwilson** [comment] 2016-07-16 23:42
To me, this bug should not be required for 1.6.0.  It's not serious, doesn't impact store customers.

**Comment by drbyte** [comment] 2016-07-17 00:16
Well, if it's throwing up errors in any *server* environments then it should be fixed. Having javascript/ajax popups with error messages doesn't make for a good user experience, whether that's customer or admin.

That said, the `console.log` can be commented out and the symptom goes away. I think the bug is in what's getting passed to it.

**Comment by lat9** [comment] 2016-09-24 15:35
FWIW, I vaguely remember coming across some type of issue with the console.log(jqXHR) statement when I was debugging the "One-Page Checkout" plugin that uses the built-in ajax.php processing.  I think (but don't **know**) that the issue had to do with the `jqXHR` variable's type.

It might have been when I was debugging that plugin's handling of request timeouts.

**Closed** 2018-09-15 17:50 UTC
Labels: Closed - No Update, [Issue Type] Possible Bug
