### ISSUE TITLE
ZC158: checkout payment php warnings, Undefined array key in ot_coupon

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#4306] opened 2021-04-29 21:37 UTC
ZC158, php8, vanilla install with demo.
Set customer address province to Florida.
Purchase product.
Checkout _payment page triggers these errors.

> [29-Apr-2021 23:30:21 Europe/Madrid] Request URI: /zencart-158/index.php?main_page=checkout_payment, IP address: 127.0.0.1
> #1  ot_coupon->get_order_total() called at [...\zencart-158\includes\modules\order_total\ot_coupon.php:79]
> #2  ot_coupon->process() called at [...\zencart-158\includes\classes\order_total.php:178]
> #3  order_total->pre_confirmation_check() called at [...\zencart-158\includes\modules\pages\checkout_payment\header_php.php:101]
> #4  require(...\zencart-158\includes\modules\pages\checkout_payment\header_php.php) called at [...\zencart-158\index.php:35]
> --> PHP Warning: Undefined array key "Sales Tax" in ...\zencart-158\includes\modules\order_total\ot_coupon.php on line 594.
> 
> [29-Apr-2021 23:30:21 Europe/Madrid] Request URI: /zencart-158/index.php?main_page=checkout_payment, IP address: 127.0.0.1
> #1  ot_coupon->get_order_total() called at [...\zencart-158\includes\modules\order_total\ot_coupon.php:79]
> #2  ot_coupon->process() called at [...\zencart-158\includes\classes\order_total.php:65]
> #3  order_total->process() called at [...\zencart-158\includes\templates\template_default\templates\tpl_checkout_payment_default.php:48]
> #4  require(...\zencart-158\includes\templates\template_default\templates\tpl_checkout_payment_default.php) called at [...\zencart-158\includes\templates\responsive_classic\common\tpl_main_page.php:178]
> #5  require(...\zencart-158\includes\templates\responsive_classic\common\tpl_main_page.php) called at [...\zencart-158\index.php:94]
> --> PHP Warning: Undefined array key "Sales Tax" in ...\zencart-158\includes\modules\order_total\ot_coupon.php on line 594.

https://github.com/zencart/zencart/blob/c6422419a9264b4102d36f6389d826b6cbee2b9a/includes/modules/order_total/ot_coupon.php#L594

**Comment by drbyte** [comment] 2021-04-30 20:15
I'm puzzled why the rate name is not set in this case.
(I did test as you described, and the warning is not triggered for me, but my current site isn't completely vanilla, as I do have other mods like OPC installed in this test site I'm using today.)

The rate names should be properly set by virtue of the order class's `cart()` method, which gets the rates via `setTaxRatesForProduct()` and then sets them into the `info` array via `calculateTaxForProduct()` here:
https://github.com/zencart/zencart/blob/9fc13790884151dffaa503de4b1aa063e54f1ab7/includes/classes/order.php#L562-L566

and `calculateTaxForProduct()` sets it into the `info` array here:
https://github.com/zencart/zencart/blob/9fc13790884151dffaa503de4b1aa063e54f1ab7/includes/classes/order.php#L691-L695

All of this is triggered via the call to `new Order;`, before the order-total code which later fires ot_coupon where you said the problem appeared.
https://github.com/zencart/zencart/blob/9fc13790884151dffaa503de4b1aa063e54f1ab7/includes/modules/pages/checkout_payment/header_php.php#L93-L101

**Comment by torvista** [comment] 2021-04-30 21:36
I always have strict reporting on too.
Thanks for the info, I'll try and look more are this.

**Comment by torvista** [comment] 2021-05-03 09:00
Subsequently I could not get this to trigger on a vanilla site...but thanks again for the detailed explanation, that helped.

So, to trigger this, add a second tax rate of 0% for another zone eg Alabama.
Change customer to Alabama and start checkout....so the info array has info for the 0% rate (tax rate 2)

The error in my first post is triggered when in ot_coupon, there is a check on the **zone** tax description but based on the **product** tax class which is "1", and so is referencing tax rate 1 which is not in the array.

https://github.com/zencart/zencart/blob/7311cd1d51247520d8f8a8bc09fe3820379bdcaa/includes/modules/order_total/ot_coupon.php#L594

**Comment by drbyte** [comment] 2021-05-04 16:18
Does this happen on 1.5.7 too?

**Comment by proseLA** [comment] 2021-05-06 14:23
i am getting similar errors on a v157 customized site.  i'm actually too buried in other projects right now to track it down...  but i have a feeling it is due to not enforcing return values from the tax module enabled.  although i very easily could be wrong.

**Comment by torvista** [comment] 2021-05-06 14:45
Returning to this install, logging in as the same customer and continuing the payment process I found the error not occurring...as happened previously. No explanation for that.

With very limited time, I'm finding this difficult to get to grips with, so here is an observation.
Vanilla installs of 157/158.
Same Matrox G200 in the cart.

With respect to the $order->info array, Step 1 shipping and step 2 payment are the same on both carts.

```
$order->info:
Array
(
    [order_status] => 1
    [currency] => EUR
    [currency_value] => 0.773000
    [payment_method] => 
    [payment_module_code] => 
    [coupon_code] => 
    [shipping_method] => Flat Rate (Best Way)
    [shipping_module_code] => flat_flat
    [shipping_cost] => 5.00
    [subtotal] => 299.99
    [shipping_tax] => 0
    [tax] => 0
    [total] => 304.99
    [tax_groups] => Array
        (
            [Sales Tax] => 0 /*NOTE THAT THIS IS UNKNOWN_SALES_TAX */
        )

    [comments] => 
    [ip_address] => 127.0.0.1 - 127.0.0.1
)
```

But in ot_coupon there is this check
157
$is_product_valid = (is_product_valid($products[$i]['id'], $couponCode) && is_coupon_valid_for_sales($products[$i]['id'], $couponCode));
158
$is_product_valid = (is_product_valid($product['id'], $coupon_id) && is_coupon_valid_for_sales($product['id'], $coupon_id)); 

The loop logic is the same/correct but the returned values are different.

157: true
158: false

and the error I am persuing in 158 is in the subsequent clause in ot_coupon for !$is_product_valid, 
so possibly this clause should not be being parsed at all.

The function is_coupon_valid_for_sales has been changed for 158 and is returning true in 157 and false in 158.

**Comment by torvista** [comment] 2021-05-18 22:04
related:https://github.com/zencart/zencart/issues/4339#issuecomment-843536619

**Comment by proseLA** [comment] 2021-05-26 15:19
@torvista i have just placed two orders on a vanilla v158 store.  now, the code has no doubt changed since when you opened this issue.  so, i can only speak to how the code is at this moment.

i am not able to reproduce the error that you talking about.  i placed an order on the testdata with a florida address and it processed correctly with the florida 7% tax.  and no debug errors came up.

with regards to creating a 0% tax rate for another state, i have no desire to even try that, as who plans to set up 0% tax rates?  it is entirely possible that the situation may result in an error, but anyone setting up a 0% tax rate should not be humored with error checking IMO.

with regards to looking at the `$order->info` array, i see no need until there is a reproducible bug (which you have done quite admirably in the past), but i do not see that one here in a vanilla install.

best.

**Comment by torvista** [comment] 2021-05-26 20:53
Since reporting this, the error has not cropped up at all on the production site....

Regarding 0% tax, this sums it up: 0% for rest of the world, same as I have.
https://www.zen-cart.com/showthread.php?213763-Digital-Seller-New-2015-EU-Digital-VAT-Affects-You&p=1265814#post1265814

**Comment by proseLA** [comment] 2021-06-09 16:29
@torvista i think it is safe to close this issue, as  #4365  hopefully addresses any problems you (and i) may have encountered.

if not, we can continue troubleshooting.

best.

**Closed** 2021-06-09 17:54 UTC
