### ISSUE TITLE
Admin index page layout is squashed

### ISSUE THREAD

**Issue by Zen4All** [zencart/zencart#1060] opened 2016-07-05 06:45 UTC
After the last updates to the admin template, my admin index page looks squashed.
![image1](https://cloud.githubusercontent.com/assets/2766593/16576031/c419a1ce-428c-11e6-9298-953e184855ec.jpg)

**Comment by zcwilt** [comment] 2016-07-05 14:21
Noted. When I redid the code, I removed the row/column classes as gridstack is supposed to manage those, but guess it still needs something to clear the floats.

**Comment by scottcwilson** [comment] 2016-07-07 23:30
I was wondering about this too just this morning.  Thanks for reporting it.

**Comment by drbyte** [comment] 2016-07-10 18:56
But ... it wasn't squashed like this when we reviewed the original PR for adding gridstack. Hmmmm...

**Comment by scottcwilson** [comment] 2016-07-10 21:10
By chance did you happen to have just the right settings in your widget layout to prevent this from happening?  Like say 3 equally tall widgets or something?

**Comment by Zen4All** [comment] 2016-07-11 13:55
I did not change any settings. They ate the defaults from the install. 
After the last PR's it is less squashed. Right now I am on a two week holiday, but after that I can help again.

**Comment by scottcwilson** [comment] 2016-07-18 10:21
Has this been fixed, or is it dependent on your widget selection and layout?  I don't see it any more, even with the same widget layout as in the original screenshot showing the error.

**Comment by drbyte** [comment] 2016-07-18 12:33
I had a similar issue. It was caused by having not rerun zc_install. (Well, actually, simply dropping and re-installing all the widget-related tables fixed it ... because the width/height values were needed.) A fresh run of zc_install cleared it up. Dev environment of course.

**Comment by scottcwilson** [comment] 2016-07-18 13:54
Suggest we close then?

**Comment by zcwilt** [comment] 2016-07-18 16:01
No code has been committed to fix this. There is therefore a chance that a particular set of widgets/positions will reproduce.

**Comment by zcwilt** [comment] 2016-07-18 18:40
Also. I think the same problem that causes the squash also cause the configuration menu to cut off

**Comment by scottcwilson** [comment] 2016-07-18 18:53
I am actually seeing this right now but my db is out of date.  I was going to rebuild my db and try it again.  I will report my findings.

**Closed** 2016-07-19 13:31 UTC
Labels: admin backend, bug, in progress
