### ISSUE TITLE
Table 'database.ezpages_content' doesn't exist

### ISSUE THREAD

**Issue by lat9** [zencart/zencart#2490] opened 2019-06-29 14:46 UTC
I'm in the process of _re-building_ a zc154 store, using the zc156b distribution as the base.  

Simple enough, right?  Start by cloning the current site's database, copying the zc156 distribution's files to a fresh file-system and modifying the zc154-era `configure.php` files to point to reference the upgrade's URL and file-system directory.

When I then pointed the installation to the `/zc_install` processing, I was met with a partial whitescreen.  Turns out that the site's current configuration uses EZ-Pages in the header, sidebox and footer locations and the zc156b EZ-pages' processing presumes the presence of the `ez_pages_content` table which, unfortunately, isn't there until the installation/upgrade completes:

```
--> PHP Fatal error: 1146:Table 'database.ezpages_content' doesn't exist :: SELECT e.*, ec.*
                                FROM ezpages e,
                                     ezpages_content ec
                                WHERE e.pages_id = ec.pages_id
                                AND ec.languages_id = 1
                                AND e.status_sidebox = 1
                                AND e.sidebox_sort_order > 0
                                ORDER BY e.sidebox_sort_order, ec.pages_title ==> (as called by) /home/store/includes/modules/sideboxes/ezpages.php on line 23 <== in /home/store/includes/classes/db/mysql/query_factory.php on line 171.
```

I was able to work-around the issue by creating a temporary file in the site's `/includes/extra_configures` directory, containing:

```php
<?php
define('EZPAGES_STATUS_HEADER', '0');
define('EZPAGES_STATUS_SIDEBOX', '0');
define('EZPAGES_STATUS_FOOTER', '0');
```

to cause the page-handling to not bring in those EZ-pages' settings until the upgrade was completed, but there's surely a better way to handle this chicken/egg situation!

**Comment by scottcwilson** [comment] 2019-06-29 15:25
@lat9 Can you post the log you got?

**Comment by lat9** [comment] 2019-06-29 15:28
Look above.

**Comment by scottcwilson** [comment] 2019-06-29 15:35
Ah LOL it got cut off and I didn't see it.

**Comment by lat9** [comment] 2019-06-29 15:37
Noting that the log I posted was for the sidebox version; there were similar logs for the header and footer.

**Comment by drbyte** [comment] 2019-06-29 15:49
> When I then pointed the installation to the `/zc_install` processing, I was met with a partial whitescreen. Turns out that the site's current configuration uses EZ-Pages in the header, sidebox and footer locations

Puzzling ... because `zc_install` doesn't fire the catalog sideboxes/header/footer.
While a visit to the catalog would certainly trigger those table-doesn't-exist errors until you run zc_install and upgrade the database, your whitescreen in zc_install would be related to something else.

**Comment by scottcwilson** [comment] 2019-06-29 15:50
added a PR just in case.

**Comment by lat9** [comment] 2019-06-29 15:55
@drbyte, I agree as I've always seen the zc_install 'take over' the storefront display.  Could it be that the pre-existing site's template (which is currently active, but not ready for the upgrade) wasn't yet ported over?

**Comment by drbyte** [comment] 2019-06-29 15:58
zc_install attempts to do an https redirect by making a curl hit to the website, and it also  test .htaccess rules by attempting to hit a file that should be denied. Both might trigger the catalog to "run", but both would be out-of-band and not "block" zc_install with a whitescreen. So, while those hits to the catalog could trigger debuglogs, I'd be looking in the zcInstall-Debug-*.log files for actual errors happening in zc_install.

**Comment by scottcwilson** [comment] 2019-06-29 15:59
Suggested repro steps: 
- put site in maintenance mode
- stage new site, updating all files but don't run zc_install - go for coffee first.
- a customer visits the store.  BANG white page instead of "Down for maintenance."

**Comment by drbyte** [comment] 2019-06-29 16:04
> Suggested repro steps:
> 
> * put site in maintenance mode
> * stage new site, updating all files but don't run zc_install - go for coffee first.
> * a customer visits the store.  BANG white page instead of "Down for maintenance."

Sure, that could happen. And probably does for those who don't stage the upgrade offline first.

But specifically it doesn't explain the real root cause of lat9's whitescreen in zc_install.

**Comment by lat9** [comment] 2019-06-29 16:12
What's weird is that I successfully did the 'install' on a local XAMPP-based setup using a clone of that database and file-system contents.  The upgrade's hosted staging site is running on PHP-FPM and there were no zcInstall*.log files generated.

**Comment by mc12345678** [comment] 2019-06-29 22:34
> The upgrade's hosted staging site is running on PHP-FPM and there were no zcInstall*.log files generated.

Were they looked for before attempting to access the admin or after? There are install logs that get deleted upon attempting access to the admin.

**Comment by lat9** [comment] 2019-06-30 11:29
_After_, just like when I did the local upgrade (which used the same db, but a different 'hosted' environment).  On my XAMPP setup, those zcInstall*.log files still exist in the /logs directory.

**Comment by lat9** [comment] 2019-07-03 19:29
I'm wondering now whether the site's use of **_Ceon URI Mapping_** had a play in this issue, as I'd copied the live site's .htaccess over prior to the upgrade and the mapping is enabled in the database.  I noticed that the `zc_install` directory is not listed as one to 'not' rewrite.

IIRC, I initially 'hit' the site as `example.com/zc_install` to receive that initial error then tried `example.com/zc_install/index.php` which also received the error.

**Comment by drbyte** [comment] 2019-07-04 19:20
I can't seem to recreate this situation, other than with illogical steps, which the PR above takes care of.
Closing for now. Post back if new information is found to explain other edge cases.

**Closed by drbyte** 2019-07-04 19:20 UTC
