### ISSUE TITLE
Bug paypalwpp: PHP Fatal error: Uncaught Error: Call to undefined method paypalwpp::payment_status() 

### ISSUE THREAD

**Issue by torvista** [zencart/zencart#3182] opened 2020-04-07 15:38 UTC
(157 vanilla files, today. php 7.3.16, mysql 5.6.45, linux2.6.32)

I've done some sandbox tests and get this error/white screen of death on order completion.
paypal logs all indicate all ok.
This happens at the  same time as the last CURL log for DoExpressCheckoutPayment.

Options:
Shortcut Button: on
Require confirmed address : no
Select cheapest shipping: no
Skip payment: no
Automatic account creation: no. Although the account that was created looks pretty permanent to me.
Final Sale EURO only, InstantOnly, Paypal, InContext, sandbox

Order process
customer not logged in,
from shopping cart, press Paypal button, browser redirected to Paypal (no Incontext popup...), authorises payment, returns and proceeds through payment process, then on pressing confirmation, death.
Have to manually navigate to another page to load shop page.
Order is recorded, confirmation email is sent/received but product remains in shopping cart.

This dev Server is available for test use.
> [07-Apr-2020 17:10:02 Europe/Madrid] PHP Fatal error: Uncaught Error: Call to undefined method paypalwpp::payment_status() in /DEV_SERVER/zencart-157/includes/modules/payment/paypalwpp.php:498
> Stack trace:
> #0 /DEV_SERVER/zencart-157/includes/classes/payment.php(254): paypalwpp->after_process()
> #1 /DEV_SERVER/zencart-157/includes/modules/pages/checkout_process/header_php.php(17): payment->after_process()
> #2 /DEV_SERVER/zencart-157/index.php(36): require('/...../...')
> #3 {main}
> thrown in /DEV_SERVER/zencart-157/includes/modules/payment/paypalwpp.php on line 498
> 
> [07-Apr-2020 17:10:02 Europe/Madrid] Request URI: /zencart-157/index.php?main_page=checkout_process, IP address: 188.171.175.201
> --> PHP Fatal error: Uncaught Error: Call to undefined method paypalwpp::payment_status() in /DEV_SERVER/zencart-157/includes/modules/payment/paypalwpp.php:498
> Stack trace:
> #0 /DEV_SERVER/zencart-157/includes/classes/payment.php(254): paypalwpp->after_process()
> #1 /DEV_SERVER/zencart-157/includes/modules/pages/checkout_process/header_php.php(17): payment->after_process()
> #2 /DEV_SERVER/zencart-157/index.php(36): require('/..../...')
> #3 {main}
> thrown in /DEV_SERVER/zencart-157/includes/modules/payment/paypalwpp.php on line 498

**Comment by drbyte** [comment] 2020-04-07 17:40
Bug caused by missing `.` in #2963 
https://github.com/zencart/zencart/commit/d1a460e92128524e62af1913cfadc97343803b34#commitcomment-38349088

**Comment by drbyte** [comment] 2020-04-07 17:43
Closed by https://github.com/zencart/zencart/commit/b19c50bf861e3e7b2f074a5225b913307d27e10d

**Closed by drbyte** 2020-04-07 17:43 UTC
