### ISSUE TITLE
v157c install SQL Patches error on admin page

### ISSUE THREAD

**Issue by sloanxue** [zencart/zencart#4338] opened 2021-05-18 07:21 UTC
**Version**
Zen Cart version: v1.5.7c
PHP version: 7.4

when I try to install sql patches as below to zencart
```
SELECT @sortorder:=max(sort_order)
FROM configuration_group;

INSERT INTO `configuration_group` VALUES (NULL, 'Sloan Review', 'Sloan Review', @sortorder+1, 1);

SELECT @reviewid:=max(configuration_group_id)
FROM configuration_group;

INSERT INTO configuration ( configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added, use_function, set_function ) VALUES ( 'Activate Sloan Review', 'ACTIVATE_SLOAN_REIVEW', 'true', 'Enables Sloan Review.', @reviewid, 10, now(), NULL, 'zen_cfg_select_option(array(\'true\', \'false\'),' );


INSERT INTO admin_pages (page_key, language_key, main_page, page_params, menu_key, display_on_menu, sort_order) VALUES ('configSloanReview', 'BOX_CONFIGURATION_SLOAN_REVIEW', 'FILENAME_CONFIGURATION', CONCAT('gID=', @reviewid), 'configuration', 'Y', 394); 
INSERT INTO admin_pages (page_key, language_key, main_page, page_params, menu_key, display_on_menu, sort_order) VALUES ('sloanreview', 'BOX_TOOLS_SLOAN_REVIEW', 'FILENAME_SLOAN_REVIEW', '', 'tools', 'Y', 394); 

CREATE TABLE IF NOT EXISTS `sloan_reviews` (
	`sloan_reviews_id` int(11) NOT NULL auto_increment,
        `sloan_reviews_status` tinyint(1) default '0',
	`sloan_reviews_content` text DEFAULT NULL,
        PRIMARY KEY  (`sloan_reviews_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 AUTO_INCREMENT=1;
```
the admin page turns to blank
and the log fies like this:
`[15-May-2021 15:25:04 Asia/Shanghai] PHP Fatal error:  Uncaught Error: Object of class queryFactoryResult could not be converted to string in E:\phpstudy_pro\WWW\z157c\console\sqlpatch.php:753
Stack trace:
#0 E:\phpstudy_pro\WWW\z157c\console\index.php(11): require()
#1 {main}
  thrown in E:\phpstudy_pro\WWW\z157c\console\sqlpatch.php on line 753

[15-May-2021 15:25:04 Asia/Shanghai] Request URI: /z157c/console/index.php?cmd=sqlpatch&action=execute, IP address: ::1

--> PHP Fatal error: Uncaught Error: Object of class queryFactoryResult could not be converted to string in E:\phpstudy_pro\WWW\z157c\console\sqlpatch.php:753
Stack trace:
#0 E:\phpstudy_pro\WWW\z157c\console\index.php(11): require()
#1 {main}
  thrown in E:\phpstudy_pro\WWW\z157c\console\sqlpatch.php on line 753.
`

I install this sql patches in phpmyadmin and z157b, both are OK.
But it error in z157c, both in local host and online host (blue host).
actually I saw the sql works on sql, but the admin page errors.

**Comment by drbyte** [comment] 2021-05-18 17:13
This is a duplicate of #4130 resolved in https://github.com/zencart/zencart/commit/77d9b255ecccde7fba0b2ab0001e630979e192f4#diff-ec9fa381f7cb7771565bd98e8a5d33c40bd764ecb05554183d725df503f9a598

**Closed by drbyte** 2021-05-18 17:13 UTC

**Comment by sloanxue** [comment] 2021-05-18 18:08
thank you
